# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  default

steps:
- task: JavaToolInstaller@0
  inputs:
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
